# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main_w = QtWidgets.QFrame(self.centralwidget)
        self.frame_main_w.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame_main_w.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_main_w.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_w.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_w.setObjectName("frame_main_w")
        self.menu_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.menu_frame_3.setGeometry(QtCore.QRect(0, -1, 200, 611))
        self.menu_frame_3.setStyleSheet("background-color: #17223b;")
        self.menu_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame_3.setObjectName("menu_frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.menu_frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 201, 611))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_Menu_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_Menu_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_Menu_3.setContentsMargins(0, 0, 1, 150)
        self.verticalLayout_Menu_3.setSpacing(2)
        self.verticalLayout_Menu_3.setObjectName("verticalLayout_Menu_3")
        self.frame_Saldo_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_Saldo_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 6px;")
        self.frame_Saldo_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Saldo_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Saldo_3.setObjectName("frame_Saldo_3")
        self.Label_Saldo_3 = QtWidgets.QLabel(self.frame_Saldo_3)
        self.Label_Saldo_3.setGeometry(QtCore.QRect(5, 9, 140, 40))
        self.Label_Saldo_3.setStyleSheet("font: 87 10pt \"Roboto Black\";")
        self.Label_Saldo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Saldo_3.setObjectName("Label_Saldo_3")
        self.pushButton_agregar_saldo_3 = QtWidgets.QPushButton(self.frame_Saldo_3)
        self.pushButton_agregar_saldo_3.setGeometry(QtCore.QRect(150, 10, 35, 35))
        self.pushButton_agregar_saldo_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_agregar_saldo_3.setStyleSheet("image: url(:/newPrefix/icons8-positive-48.png);")
        self.pushButton_agregar_saldo_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_img/icons8-positive-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_agregar_saldo_3.setIcon(icon)
        self.pushButton_agregar_saldo_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_agregar_saldo_3.setObjectName("pushButton_agregar_saldo_3")
        self.verticalLayout_Menu_3.addWidget(self.frame_Saldo_3)
        self.frame_Deuda_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_Deuda_3.setStyleSheet("background-color: rgb(255, 103, 104);\n"
"border-radius: 6px;")
        self.frame_Deuda_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Deuda_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Deuda_3.setObjectName("frame_Deuda_3")
        self.Label_Deuda_3 = QtWidgets.QLabel(self.frame_Deuda_3)
        self.Label_Deuda_3.setGeometry(QtCore.QRect(10, 18, 181, 20))
        self.Label_Deuda_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Roboto Black\";")
        self.Label_Deuda_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Label_Deuda_3.setScaledContents(False)
        self.Label_Deuda_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Deuda_3.setWordWrap(False)
        self.Label_Deuda_3.setIndent(-1)
        self.Label_Deuda_3.setObjectName("Label_Deuda_3")
        self.verticalLayout_Menu_3.addWidget(self.frame_Deuda_3)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_Menu_3.addWidget(self.line_3)
        self.pushButton_Inicio_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Inicio_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Inicio_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Inicio_3.setSizePolicy(sizePolicy)
        self.pushButton_Inicio_3.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_Inicio_3.setFont(font)
        self.pushButton_Inicio_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Inicio_3.setStyleSheet("background-color: #6b778d;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius: 6px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon_img/icons8-google-home-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inicio_3.setIcon(icon1)
        self.pushButton_Inicio_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Inicio_3.setObjectName("pushButton_Inicio_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Inicio_3)
        self.pushButton_Resumen_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Resumen_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Resumen_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Resumen_3.setSizePolicy(sizePolicy)
        self.pushButton_Resumen_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_Resumen_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Resumen_3.setStyleSheet("background-color: #6b778d;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius: 6px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon_img/icons8-spreadsheet-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Resumen_3.setIcon(icon2)
        self.pushButton_Resumen_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Resumen_3.setObjectName("pushButton_Resumen_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Resumen_3)
        self.pushButton_Categorias_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Categorias_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Categorias_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Categorias_3.setSizePolicy(sizePolicy)
        self.pushButton_Categorias_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_Categorias_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Categorias_3.setStyleSheet("background-color: #6b778d;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius: 6px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon_img/icons8-sorting-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Categorias_3.setIcon(icon3)
        self.pushButton_Categorias_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Categorias_3.setObjectName("pushButton_Categorias_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Categorias_3)
        self.pushButton_Historial_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Historial_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Historial_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Historial_3.setSizePolicy(sizePolicy)
        self.pushButton_Historial_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_Historial_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Historial_3.setStyleSheet("background-color: #6b778d;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius: 6px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon_img/icons8-statistics-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Historial_3.setIcon(icon4)
        self.pushButton_Historial_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Historial_3.setObjectName("pushButton_Historial_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Historial_3)
        self.pushButton_Estadisticas_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Estadisticas_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Estadisticas_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Estadisticas_3.setSizePolicy(sizePolicy)
        self.pushButton_Estadisticas_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_Estadisticas_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Estadisticas_3.setStyleSheet("background-color: #6b778d;\n"
"color: rgb(255, 255, 255);\n"
"font: 57 14pt \"Roboto Medium\";\n"
"border-radius: 6px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon_img/icons8-doughnut-chart-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Estadisticas_3.setIcon(icon5)
        self.pushButton_Estadisticas_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Estadisticas_3.setCheckable(False)
        self.pushButton_Estadisticas_3.setChecked(False)
        self.pushButton_Estadisticas_3.setAutoRepeat(False)
        self.pushButton_Estadisticas_3.setAutoExclusive(False)
        self.pushButton_Estadisticas_3.setObjectName("pushButton_Estadisticas_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Estadisticas_3)
        self.pushButton_Ayuda_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_Ayuda_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Ayuda_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Ayuda_3.setSizePolicy(sizePolicy)
        self.pushButton_Ayuda_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_Ayuda_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Ayuda_3.setStyleSheet("background-color: #6b778d;\n"
"font: 57 14pt \"Roboto Medium\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 6px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon_img/icons8-help-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Ayuda_3.setIcon(icon6)
        self.pushButton_Ayuda_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Ayuda_3.setObjectName("pushButton_Ayuda_3")
        self.verticalLayout_Menu_3.addWidget(self.pushButton_Ayuda_3)
        self.inicio_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.inicio_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.inicio_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inicio_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inicio_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inicio_frame_3.setObjectName("inicio_frame_3")
        self.label_6 = QtWidgets.QLabel(self.inicio_frame_3)
        self.label_6.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_27 = QtWidgets.QLabel(self.inicio_frame_3)
        self.label_27.setGeometry(QtCore.QRect(270, 40, 31, 16))
        self.label_27.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_27.setObjectName("label_27")
        self.resumen_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.resumen_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.resumen_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resumen_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resumen_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resumen_frame_3.setObjectName("resumen_frame_3")
        self.label_28 = QtWidgets.QLabel(self.resumen_frame_3)
        self.label_28.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_28.setStyleSheet("background: transparent;")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.resumen_frame_3)
        self.label_29.setGeometry(QtCore.QRect(270, 40, 51, 16))
        self.label_29.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_29.setObjectName("label_29")
        self.categorias_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.categorias_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.categorias_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.categorias_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.categorias_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.categorias_frame_3.setObjectName("categorias_frame_3")
        self.label_30 = QtWidgets.QLabel(self.categorias_frame_3)
        self.label_30.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_30.setStyleSheet("background: transparent;")
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.categorias_frame_3)
        self.label_31.setGeometry(QtCore.QRect(270, 40, 71, 16))
        self.label_31.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_31.setObjectName("label_31")
        self.estadisticas_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.estadisticas_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.estadisticas_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.estadisticas_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.estadisticas_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.estadisticas_frame_3.setObjectName("estadisticas_frame_3")
        self.label_32 = QtWidgets.QLabel(self.estadisticas_frame_3)
        self.label_32.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_32.setStyleSheet("background: transparent;")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.estadisticas_frame_3)
        self.label_33.setGeometry(QtCore.QRect(270, 40, 81, 16))
        self.label_33.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_33.setObjectName("label_33")
        self.ayuda_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.ayuda_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.ayuda_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ayuda_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayuda_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayuda_frame_3.setObjectName("ayuda_frame_3")
        self.label_34 = QtWidgets.QLabel(self.ayuda_frame_3)
        self.label_34.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_34.setStyleSheet("background: transparent;")
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.ayuda_frame_3)
        self.label_35.setGeometry(QtCore.QRect(270, 40, 41, 16))
        self.label_35.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_35.setObjectName("label_35")
        self.historial_frame_3 = QtWidgets.QFrame(self.frame_main_w)
        self.historial_frame_3.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.historial_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.historial_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.historial_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.historial_frame_3.setObjectName("historial_frame_3")
        self.label_36 = QtWidgets.QLabel(self.historial_frame_3)
        self.label_36.setGeometry(QtCore.QRect(50, -30, 983, 982))
        self.label_36.setStyleSheet("background: transparent;")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_oficial_vector_bl.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.historial_frame_3)
        self.label_37.setGeometry(QtCore.QRect(270, 40, 61, 16))
        self.label_37.setStyleSheet("font: 87 8pt \"Roboto Black\";")
        self.label_37.setObjectName("label_37")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_Saldo_3.setText(_translate("MainWindow", "Saldo: $00000.00"))
        self.Label_Deuda_3.setText(_translate("MainWindow", "Deuda: $00000.00"))
        self.pushButton_Inicio_3.setText(_translate("MainWindow", "Inicio"))
        self.pushButton_Resumen_3.setText(_translate("MainWindow", "Resumen"))
        self.pushButton_Categorias_3.setText(_translate("MainWindow", "Categorías"))
        self.pushButton_Historial_3.setText(_translate("MainWindow", "Historial"))
        self.pushButton_Estadisticas_3.setText(_translate("MainWindow", "Estadísticas"))
        self.pushButton_Ayuda_3.setText(_translate("MainWindow", "Ayuda"))
        self.label_27.setText(_translate("MainWindow", "INICIO"))
        self.label_29.setText(_translate("MainWindow", "RESUMEN"))
        self.label_31.setText(_translate("MainWindow", "CATEGORIAS"))
        self.label_33.setText(_translate("MainWindow", "ESTADISTICAS"))
        self.label_35.setText(_translate("MainWindow", "AYUDA"))
        self.label_37.setText(_translate("MainWindow", "HISTORIAL"))


#import Img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
